replicaCount: 1

image:
  repository: ai-inference-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"

  limits:
    memory: "1Gi"
    cpu: "500m"

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 20
  timeoutSeconds: 5

ingress:
  enabled: true
  className: nginx
  host: ai.local

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 5